# automation.button_plus_initialize
alias: Button Plus Entrance | Initialize Labels/LEDs
description: "Call publish states script when last button is configured"
triggers:
  - topic: homeassistant/event/buttonplus_Entrance_button_8-1_pushbutton/config #8-1 last button
    qos: 0
    trigger: mqtt
actions:
  - action: script.publish_states
    data: {}
mode: single
